name: mysql-stack

services:
  mysql-server-80:
    image: mysql/mysql-server:8.0
    volumes:
      - ./vol/db:/var/lib/mysql
      - ./vol/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=% 